name: Luca Foschini
description: Data Hacker
meta_description: "Luca Foschini's personal pages"
baseurl: '/'

markdown: redcarpet
pygments: true

author:         
  name: 'Luca Foschini'
  website: 'http://lucafoschini.com'
  bio: ''
  image: 'images/headshot.jpg'

# Details for the RSS feed generator
url:            'http://lucafoschini.com'
