name: Luca Foschini
description: Data Scientist
meta_description: "Luca Foschini's personal pages"
baseurl: ''

markdown: redcarpet
pygments: true

author:         
  name: 'Luca Foschini'
  website: 'http://lucafoschini.com'
  bio: 'Founder and data scientist at <a href="http://www.theactivityexchange.com/">The Activity Exchange</a>.<br>Ph.D in Computer Science from UCSB'
  image: '/images/headshot.jpg'
  image_basename: '/images/headshot'

# Details for the RSS feed generator
url:            'http://lucafoschini.com'
